name: Integrate with release
on:
  push:
    branches:
      - master
      
jobs:
  push-to-release:
    runs-on: ubuntu-latest

    steps:
      - name: Push to release
        run: |
          echo "merging with release branch..."

