name: Release to Heroku
on:
  push:
    branches:
      - release
      
jobs:
  release-to-heroku:
    runs-on: ubuntu-latest

    steps:
      - name: Push to release
        run: |
          echo "releasing..."

